version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      # Port for your applications to connect to RabbitMQ
      - "5672:5672"
      # Port for the web-based management UI
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local