
FROM vllm/vllm-openai:v0.5.1


WORKDIR /app


RUN useradd -ms /bin/bash -u 1001 vllmuser
USER vllmuser



COPY --chown=vllmuser:vllmuser requirements.txt .


RUN pip3 install --no-cache-dir -r requirements.txt



COPY --chown=vllmuser:vllmuser service/ai_services/ .



EXPOSE 8001


HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl --fail http://localhost:8001/docs || exit 1




ENTRYPOINT ["python3"]


CMD ["ai_server.py"]